set(UNITY_MAJOR "6000")
set(UNITY_MINOR "0")
set(UNITY_PATCH "62")
set(UNITY_DECORATOR "f1")

set(UNITY_DIRECTORY "C:\\Program Files\\Unity\\Hub\\Editor\\${UNITY_MAJOR}.${UNITY_MINOR}.${UNITY_PATCH}${UNITY_DECORATOR}")

set(UNITY_MAJOR_AGNOSTIC OFF) # not recommended
set(UNITY_MINOR_AGNOSTIC OFF) # not as bad
set(UNITY_PATCH_AGNOSTIC ON) # probably fine